/** @format */

export const actionsTypes = {
  GET_POST_FROM_API: "GET_POST_FROM_API",
  LIKE_OR_UNLIKE_POST: "LIKE_OR_UNLIKE_POST",
  ADD_TO_TEMPORARY_COMMENT_BOARD: "ADD_TO_TEMPORARY_COMMENT_BOARD",
  LIKE_OR_UNLIKE_COMMENT: "LIKE_OR_UNLIKE_COMMENT",
};
